# Generated by Django 4.2.2 on 2023-07-19 11:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("restapp", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task",
            old_name="task_desk",
            new_name="task_desc",
        ),
    ]
