# Generated by Django 4.2.2 on 2023-07-19 18:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restapp", "0002_rename_task_desk_task_task_desc"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="date_created",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
