# Generated by Django 4.2.2 on 2023-07-19 18:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restapp", "0003_alter_task_date_created"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="completed",
            field=models.BooleanField(default=False),
        ),
    ]
